/**
 * IRS Form 8949 PDF Generator
 *
 * Generates a proper Form 8949-style PDF from tax transaction data.
 * Uses jsPDF (already a project dependency) to create the document.
 */

import jsPDF from 'jspdf';

export interface Form8949Transaction {
  description: string;       // (a) Description of property
  dateAcquired: string;      // (b) Date acquired
  dateSold: string;          // (c) Date sold or disposed of
  proceeds: number;          // (d) Proceeds
  costBasis: number;         // (e) Cost or other basis
  adjustmentCode: string;    // (f) Code(s) from instructions
  adjustmentAmount: number;  // (g) Amount of adjustment
  gainOrLoss: number;        // (h) Gain or (loss)
}

export interface Form8949Data {
  taxYear: number;
  taxpayerName: string;
  taxpayerSSN: string; // masked for privacy
  shortTermTransactions: Form8949Transaction[];
  longTermTransactions: Form8949Transaction[];
}

const PAGE_WIDTH = 215.9; // Letter size in mm
const PAGE_HEIGHT = 279.4;
const MARGIN = 15;
const COL_WIDTHS = [45, 22, 22, 25, 25, 12, 18, 22]; // Column widths
const ROW_HEIGHT = 5.5;

function drawHeader(doc: jsPDF, data: Form8949Data, part: 'I' | 'II', pageNum: number) {
  const y = MARGIN;

  // Title
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Form 8949', MARGIN, y);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(`(Rev. December ${data.taxYear})`, MARGIN + 30, y);

  doc.setFontSize(7);
  doc.text('Department of the Treasury', PAGE_WIDTH - MARGIN, y - 3, { align: 'right' });
  doc.text('Internal Revenue Service', PAGE_WIDTH - MARGIN, y + 1, { align: 'right' });

  // Form title
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Sales and Other Dispositions of Capital Assets', PAGE_WIDTH / 2, y + 8, { align: 'center' });

  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.text(`Attach to Schedule D to list your transactions for lines 1b, 2, 3, 8b, 9, and 10.`, PAGE_WIDTH / 2, y + 13, { align: 'center' });

  // Taxpayer info
  doc.setFontSize(9);
  doc.text(`Name(s) shown on return: ${data.taxpayerName || '_______________'}`, MARGIN, y + 22);
  doc.text(`Social security number: ${data.taxpayerSSN || 'XXX-XX-XXXX'}`, PAGE_WIDTH - MARGIN - 60, y + 22);

  // Part label
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  const partTitle = part === 'I'
    ? 'Part I — Short-Term Capital Gains and Losses (Assets Held One Year or Less)'
    : 'Part II — Long-Term Capital Gains and Losses (Assets Held More Than One Year)';
  doc.text(partTitle, MARGIN, y + 32);

  // Checkbox
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.text('Check Box A, B, or C for the type of transaction:', MARGIN, y + 37);
  doc.text('[X] (A) Short-term transactions reported on Form(s) 1099-B showing basis was reported to IRS', MARGIN + 3, y + 42);

  // Generated notice
  doc.setFontSize(6);
  doc.setFont('helvetica', 'italic');
  doc.text(
    `Generated by CryptoReportKit — Page ${pageNum} — FOR INFORMATIONAL PURPOSES ONLY — Verify with a tax professional`,
    PAGE_WIDTH / 2,
    y + 48,
    { align: 'center' },
  );

  return y + 52;
}

function drawTableHeader(doc: jsPDF, startY: number): number {
  const y = startY;
  const headers = [
    '(a) Description of\nproperty',
    '(b) Date\nacquired',
    '(c) Date sold\nor disposed',
    '(d) Proceeds\n(sales price)',
    '(e) Cost or\nother basis',
    '(f)\nCode',
    '(g) Amount\nof adjustment',
    '(h) Gain or\n(loss)',
  ];

  doc.setFontSize(6);
  doc.setFont('helvetica', 'bold');

  // Draw header row background
  let x = MARGIN;
  doc.setFillColor(240, 240, 240);
  doc.rect(MARGIN, y, COL_WIDTHS.reduce((a, b) => a + b, 0), 10, 'F');

  for (let i = 0; i < headers.length; i++) {
    const lines = headers[i].split('\n');
    doc.text(lines[0], x + 1, y + 3.5);
    if (lines[1]) doc.text(lines[1], x + 1, y + 7);
    x += COL_WIDTHS[i];
  }

  // Draw header border
  doc.setDrawColor(0);
  doc.setLineWidth(0.3);
  doc.rect(MARGIN, y, COL_WIDTHS.reduce((a, b) => a + b, 0), 10);

  // Draw vertical lines
  x = MARGIN;
  for (let i = 0; i < COL_WIDTHS.length - 1; i++) {
    x += COL_WIDTHS[i];
    doc.line(x, y, x, y + 10);
  }

  return y + 10;
}

function drawTransactionRow(doc: jsPDF, tx: Form8949Transaction, y: number, rowIndex: number) {
  const fmt = (n: number) => {
    const abs = Math.abs(n);
    const str = abs.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    return n < 0 ? `(${str})` : str;
  };

  const values = [
    tx.description.length > 28 ? tx.description.slice(0, 28) + '...' : tx.description,
    tx.dateAcquired,
    tx.dateSold,
    fmt(tx.proceeds),
    fmt(tx.costBasis),
    tx.adjustmentCode || '',
    tx.adjustmentAmount !== 0 ? fmt(tx.adjustmentAmount) : '',
    fmt(tx.gainOrLoss),
  ];

  doc.setFontSize(6);
  doc.setFont('helvetica', 'normal');

  // Alternate row shading
  if (rowIndex % 2 === 0) {
    doc.setFillColor(250, 250, 250);
    doc.rect(MARGIN, y, COL_WIDTHS.reduce((a, b) => a + b, 0), ROW_HEIGHT, 'F');
  }

  // Draw row
  let x = MARGIN;
  for (let i = 0; i < values.length; i++) {
    const align = i >= 3 ? 'right' : 'left';
    const textX = align === 'right' ? x + COL_WIDTHS[i] - 1.5 : x + 1;
    doc.text(values[i], textX, y + ROW_HEIGHT - 1.5, { align: align as 'left' | 'right' });
    x += COL_WIDTHS[i];
  }

  // Draw borders
  doc.setDrawColor(200);
  doc.setLineWidth(0.1);
  doc.rect(MARGIN, y, COL_WIDTHS.reduce((a, b) => a + b, 0), ROW_HEIGHT);

  x = MARGIN;
  for (let i = 0; i < COL_WIDTHS.length - 1; i++) {
    x += COL_WIDTHS[i];
    doc.line(x, y, x, y + ROW_HEIGHT);
  }
}

function drawTotalsRow(doc: jsPDF, transactions: Form8949Transaction[], y: number): number {
  const totalProceeds = transactions.reduce((s, t) => s + t.proceeds, 0);
  const totalCostBasis = transactions.reduce((s, t) => s + t.costBasis, 0);
  const totalGainLoss = transactions.reduce((s, t) => s + t.gainOrLoss, 0);

  const fmt = (n: number) => {
    const abs = Math.abs(n);
    const str = abs.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    return n < 0 ? `(${str})` : str;
  };

  doc.setFillColor(230, 240, 230);
  doc.rect(MARGIN, y, COL_WIDTHS.reduce((a, b) => a + b, 0), ROW_HEIGHT + 1, 'F');

  doc.setFontSize(7);
  doc.setFont('helvetica', 'bold');
  doc.text('Totals', MARGIN + 1, y + ROW_HEIGHT - 1);

  let x = MARGIN;
  for (let i = 0; i < 3; i++) x += COL_WIDTHS[i];
  doc.text(fmt(totalProceeds), x + COL_WIDTHS[3] - 1.5, y + ROW_HEIGHT - 1, { align: 'right' });
  x += COL_WIDTHS[3];
  doc.text(fmt(totalCostBasis), x + COL_WIDTHS[4] - 1.5, y + ROW_HEIGHT - 1, { align: 'right' });
  x += COL_WIDTHS[4] + COL_WIDTHS[5] + COL_WIDTHS[6];
  doc.text(fmt(totalGainLoss), x + COL_WIDTHS[7] - 1.5, y + ROW_HEIGHT - 1, { align: 'right' });

  doc.setDrawColor(0);
  doc.setLineWidth(0.3);
  doc.rect(MARGIN, y, COL_WIDTHS.reduce((a, b) => a + b, 0), ROW_HEIGHT + 1);

  return y + ROW_HEIGHT + 3;
}

export function generateForm8949PDF(data: Form8949Data): jsPDF {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' });
  let pageNum = 1;

  // Part I — Short-Term
  if (data.shortTermTransactions.length > 0) {
    let y = drawHeader(doc, data, 'I', pageNum);
    y = drawTableHeader(doc, y);

    for (let i = 0; i < data.shortTermTransactions.length; i++) {
      if (y + ROW_HEIGHT > PAGE_HEIGHT - 30) {
        // New page
        doc.addPage();
        pageNum++;
        y = drawHeader(doc, data, 'I', pageNum);
        y = drawTableHeader(doc, y);
      }
      drawTransactionRow(doc, data.shortTermTransactions[i], y, i);
      y += ROW_HEIGHT;
    }

    y = drawTotalsRow(doc, data.shortTermTransactions, y + 2);
  }

  // Part II — Long-Term
  if (data.longTermTransactions.length > 0) {
    doc.addPage();
    pageNum++;
    let y = drawHeader(doc, data, 'II', pageNum);
    y = drawTableHeader(doc, y);

    for (let i = 0; i < data.longTermTransactions.length; i++) {
      if (y + ROW_HEIGHT > PAGE_HEIGHT - 30) {
        doc.addPage();
        pageNum++;
        y = drawHeader(doc, data, 'II', pageNum);
        y = drawTableHeader(doc, y);
      }
      drawTransactionRow(doc, data.longTermTransactions[i], y, i);
      y += ROW_HEIGHT;
    }

    y = drawTotalsRow(doc, data.longTermTransactions, y + 2);
  }

  return doc;
}

/**
 * Download Form 8949 as PDF in the browser.
 */
export function downloadForm8949PDF(data: Form8949Data): void {
  const doc = generateForm8949PDF(data);
  doc.save(`Form-8949-${data.taxYear}.pdf`);
}
