import type { PersonaId, PersonaDefinition } from './types';

export const PERSONA_DEFINITIONS: Record<PersonaId, PersonaDefinition> = {
  'casual-investor': {
    id: 'casual-investor',
    name: 'Casual Investor',
    tagline: 'Track your holdings and stay informed',
    description:
      'You hold crypto long-term and check in weekly. You want a simple portfolio overview, price alerts, and market summaries without the noise.',
    icon: 'TrendingUp',
    color: 'emerald',
    primaryDashboards: [
      'market-overview',
      'bitcoin',
      'portfolio',
      'performance-overview',
      'watchlist',
      'morning-snapshot',
      'quick-pulse',
    ],
    secondaryDashboards: [
      'ethereum',
      'altcoin-radar',
      'altseason-index',
      'marketcap-tracker',
      'bear-market-survival',
      'crypto-indices',
      'btc-dominance-timer',
      'stablecoin-monitor',
    ],
    primaryTools: ['/compare', '/trending', '/heatmap'],
    primaryTemplates: ['portfolio-starter', 'market-overview'],
    quickActions: [
      {
        label: 'Check Portfolio',
        href: '/live-dashboards/portfolio',
        icon: 'Wallet',
        description: 'See your holdings and P&L at a glance',
      },
      {
        label: 'Price Alerts',
        href: '/live-dashboards/watchlist',
        icon: 'Bell',
        description: 'Set up alerts for your favorite coins',
      },
      {
        label: 'Morning Snapshot',
        href: '/live-dashboards/morning-snapshot',
        icon: 'Sunrise',
        description: 'Quick daily market summary',
      },
    ],
    suggestedWorkflow: [
      {
        step: 1,
        title: 'Set up your portfolio',
        description: 'Add your holdings to track performance',
        href: '/live-dashboards/portfolio',
      },
      {
        step: 2,
        title: 'Create a watchlist',
        description: 'Track coins you are interested in',
        href: '/live-dashboards/watchlist',
      },
      {
        step: 3,
        title: 'Check your morning snapshot',
        description: 'Start each day with a quick market overview',
        href: '/live-dashboards/morning-snapshot',
      },
    ],
  },

  'active-trader': {
    id: 'active-trader',
    name: 'Active Trader',
    tagline: 'Charts, screeners, and trading signals',
    description:
      'You trade daily or weekly. You need technical analysis, screeners, derivatives data, and fast access to charts and signals.',
    icon: 'CandlestickChart',
    color: 'blue',
    primaryDashboards: [
      'trader',
      'technical-analysis',
      'technical-screener',
      'derivatives-overview',
      'funding-liquidation',
      'volume-leaders',
      'smart-screener',
      'accumulation-zone',
      'divergence-spotter',
    ],
    secondaryDashboards: [
      'market-overview',
      'bitcoin',
      'btc-vs-eth',
      'meme-coin-spotlight',
      'meme-coin-momentum',
      'volatility-regime',
      'funding-arbitrage',
      'derivatives-leverage',
      'gainers-losers',
    ],
    primaryTools: ['/screener', '/charts', '/technical', '/heatmap'],
    primaryTemplates: ['trader-charts', 'screener-watchlist'],
    quickActions: [
      {
        label: 'Technical Screener',
        href: '/live-dashboards/technical-screener',
        icon: 'ScanSearch',
        description: 'Find coins matching your technical criteria',
      },
      {
        label: 'Open Charts',
        href: '/charts',
        icon: 'BarChart3',
        description: 'Interactive chart library',
      },
      {
        label: 'Derivatives',
        href: '/live-dashboards/derivatives-overview',
        icon: 'LineChart',
        description: 'Funding rates, liquidations, and leverage',
      },
    ],
    suggestedWorkflow: [
      {
        step: 1,
        title: 'Scan the market',
        description: 'Use the screener to find setups',
        href: '/screener',
      },
      {
        step: 2,
        title: 'Analyze technicals',
        description: 'Check RSI, MACD, and moving averages',
        href: '/live-dashboards/technical-analysis',
      },
      {
        step: 3,
        title: 'Monitor derivatives',
        description: 'Track funding rates and liquidation levels',
        href: '/live-dashboards/derivatives-overview',
      },
    ],
  },

  'defi-explorer': {
    id: 'defi-explorer',
    name: 'DeFi Explorer',
    tagline: 'Yield farming, TVL, and protocol analytics',
    description:
      'You explore DeFi protocols, track yields, and research TVL trends. You want protocol-level analytics and DEX data.',
    icon: 'Layers',
    color: 'purple',
    primaryDashboards: [
      'defi-tracker',
      'defi-deep-dive',
      'defi-yield-explorer',
      'tvl-fundamentals',
      'dex-analytics',
      'stablecoin-monitor',
      'stablecoin-capital',
      'layer-2-scorecard',
      'multi-chain-bridge',
    ],
    secondaryDashboards: [
      'protocol-aave',
      'protocol-uniswap',
      'protocol-lido',
      'protocol-makerdao',
      'protocol-compound',
      'rwa-tracker',
      'layer1-compare',
      'nft-gaming',
      'ethereum',
    ],
    primaryTools: ['/defi', '/dex-pools', '/correlation'],
    primaryTemplates: ['defi-tvl', 'stablecoin-monitor'],
    quickActions: [
      {
        label: 'DeFi Tracker',
        href: '/live-dashboards/defi-tracker',
        icon: 'Landmark',
        description: 'Overview of top DeFi protocols and TVL',
      },
      {
        label: 'Yield Explorer',
        href: '/live-dashboards/defi-yield-explorer',
        icon: 'Sprout',
        description: 'Find the best yields across protocols',
      },
      {
        label: 'DEX Analytics',
        href: '/live-dashboards/dex-analytics',
        icon: 'ArrowLeftRight',
        description: 'Volume, liquidity, and pool data',
      },
    ],
    suggestedWorkflow: [
      {
        step: 1,
        title: 'Check DeFi overview',
        description: 'See top protocols by TVL and trends',
        href: '/live-dashboards/defi-tracker',
      },
      {
        step: 2,
        title: 'Explore yields',
        description: 'Compare yields across chains and protocols',
        href: '/live-dashboards/defi-yield-explorer',
      },
      {
        step: 3,
        title: 'Analyze a protocol',
        description: 'Deep-dive into a specific DeFi protocol',
        href: '/live-dashboards/protocol-aave',
      },
    ],
  },

  'analyst-researcher': {
    id: 'analyst-researcher',
    name: 'Analyst / Researcher',
    tagline: 'Data-driven analysis and report generation',
    description:
      'You produce research reports and need correlation matrices, risk metrics, data exports, and the ability to generate professional report packs.',
    icon: 'FlaskConical',
    color: 'amber',
    primaryDashboards: [
      'executive-summary',
      'correlation-matrix',
      'risk-volatility',
      'risk-return-map',
      'risk-regime',
      'market-breadth',
      'sector-analysis',
      'sector-alpha',
      'intelligence-hub',
      'historical-analysis',
    ],
    secondaryDashboards: [
      'market-overview',
      'bitcoin',
      'supply-analysis',
      'social-sentiment',
      'sentiment-pulse',
      'whale-watch',
      'whale-accumulation',
      'exchange-tracker',
      'exchange-flow',
      'cycle-comparison',
      'narrative-rotation',
    ],
    primaryTools: ['/correlation', '/risk', '/screener', '/compare'],
    primaryTemplates: ['risk-correlation', 'coin-research', 'market-overview'],
    quickActions: [
      {
        label: 'Correlation Matrix',
        href: '/live-dashboards/correlation-matrix',
        icon: 'Grid3X3',
        description: 'Cross-asset correlation analysis',
      },
      {
        label: 'Risk Analysis',
        href: '/live-dashboards/risk-volatility',
        icon: 'ShieldAlert',
        description: 'Volatility, drawdown, and risk metrics',
      },
      {
        label: 'Command Center',
        href: '/command-center',
        icon: 'LayoutDashboard',
        description: 'Generate report packs and manage workspaces',
      },
    ],
    suggestedWorkflow: [
      {
        step: 1,
        title: 'Review executive summary',
        description: 'Get the high-level market picture',
        href: '/live-dashboards/executive-summary',
      },
      {
        step: 2,
        title: 'Run risk analysis',
        description: 'Check correlations, volatility, and risk-return',
        href: '/live-dashboards/risk-volatility',
      },
      {
        step: 3,
        title: 'Generate a report pack',
        description: 'Export professional PDF + Excel reports',
        href: '/command-center',
      },
    ],
  },

  'freelancer-consultant': {
    id: 'freelancer-consultant',
    name: 'Freelancer / Consultant',
    tagline: 'Client-ready deliverables in minutes',
    description:
      'You create crypto reports for clients. You need branded templates, workspace management, and the ability to export professional packs quickly.',
    icon: 'Briefcase',
    color: 'cyan',
    primaryDashboards: [
      'executive-summary',
      'morning-snapshot',
      'market-overview',
      'portfolio',
      'watchlist',
      'pl-tracker',
    ],
    secondaryDashboards: [
      'bitcoin',
      'performance-overview',
      'correlation-matrix',
      'risk-volatility',
      'sector-analysis',
      'crypto-indices',
      'historical-analysis',
    ],
    primaryTools: ['/compare', '/heatmap', '/screener'],
    primaryTemplates: [
      'portfolio-starter',
      'market-overview',
      'coin-research',
      'risk-correlation',
    ],
    quickActions: [
      {
        label: 'Download Templates',
        href: '/downloads',
        icon: 'Download',
        description: 'Get Excel templates for client reports',
      },
      {
        label: 'Command Center',
        href: '/command-center',
        icon: 'LayoutDashboard',
        description: 'Manage workspaces and generate report packs',
      },
      {
        label: 'Market Report',
        href: '/live-dashboards/executive-summary',
        icon: 'FileText',
        description: 'Generate a quick market executive summary',
      },
    ],
    suggestedWorkflow: [
      {
        step: 1,
        title: 'Create a workspace',
        description: 'Set up a workspace for each client',
        href: '/command-center',
      },
      {
        step: 2,
        title: 'Refresh data',
        description: 'Pull the latest market data with one click',
        href: '/command-center',
      },
      {
        step: 3,
        title: 'Export report pack',
        description: 'Generate PDF + Excel + CSV bundle for your client',
        href: '/command-center',
      },
    ],
  },

  'fund-manager': {
    id: 'fund-manager',
    name: 'Fund / Portfolio Manager',
    tagline: 'Multi-portfolio risk and compliance',
    description:
      'You manage institutional or multi-asset crypto portfolios. You need risk metrics, tax reports, compliance exports, and portfolio-level analytics.',
    icon: 'Building2',
    color: 'rose',
    primaryDashboards: [
      'portfolio',
      'risk-volatility',
      'risk-return-map',
      'risk-regime',
      'tax-portfolio',
      'pl-tracker',
      'exchange-portfolio',
      'correlation-matrix',
      'market-breadth',
      'volatility-regime',
    ],
    secondaryDashboards: [
      'executive-summary',
      'market-overview',
      'whale-watch',
      'whale-accumulation',
      'exchange-flow',
      'smart-money-tracker',
      'derivatives-overview',
      'stablecoin-capital',
      'crypto-indices',
      'cycle-comparison',
    ],
    primaryTools: ['/risk', '/correlation', '/compare', '/etf'],
    primaryTemplates: ['risk-correlation', 'portfolio-starter', 'market-overview'],
    quickActions: [
      {
        label: 'Portfolio Overview',
        href: '/live-dashboards/portfolio',
        icon: 'PieChart',
        description: 'View portfolio allocation and performance',
      },
      {
        label: 'Risk Dashboard',
        href: '/live-dashboards/risk-volatility',
        icon: 'ShieldAlert',
        description: 'Monitor volatility, drawdown, and risk metrics',
      },
      {
        label: 'Tax & Compliance',
        href: '/live-dashboards/tax-portfolio',
        icon: 'FileCheck',
        description: 'Tax reporting and compliance exports',
      },
    ],
    suggestedWorkflow: [
      {
        step: 1,
        title: 'Review portfolio',
        description: 'Check allocation, P&L, and performance',
        href: '/live-dashboards/portfolio',
      },
      {
        step: 2,
        title: 'Assess risk',
        description: 'Analyze volatility, correlations, and risk-return',
        href: '/live-dashboards/risk-volatility',
      },
      {
        step: 3,
        title: 'Generate compliance report',
        description: 'Export tax and compliance data',
        href: '/live-dashboards/tax-portfolio',
      },
    ],
  },
};

export const PERSONA_LIST: PersonaDefinition[] = Object.values(PERSONA_DEFINITIONS);
